---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: metallb
      version: 0.13.9
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
  maxHistory: 9
  install:
    createNamespace: true
    remediation:
      retries: 9
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 9
  uninstall:
    keepHistory: false
  values:
    crds:
      enabled: true
