apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
data:
    TUNNEL_ID: ENC[AES256_GCM,data:icUO4BIsTOIRp9eef42bv9pXUwGeg0WQQ2xwVoJa1j0p/xwD,iv:AXr+B3LbOSI2XNhbOumPo2HGnFaKf/4Zbl5r4vFPrQo=,tag:bL6QoqHED4UPszZSq/uhkg==,type:str]
    credentials.json: ENC[AES256_GCM,data:XzncTX3WP6cOeVGYUWnjAcT/LGB93bdBz061FVYHu6GuivhT/kTWllEkj+RCtM4ywg9NDy4PjzwfDLe8YYhmDISRTVHcPqyXfi/RlVFkdxEMADCRtkP75+tpSJkwvxOfr25eDklmXMjcLGdzr+riPqThgHLvIn9jmcnh/DzrBevdvo4gAWzR+OU3cOjM59UokwIOJDtnT9oSKWFPIGEaSUuIv16dpGhkZwUdmRukyQ==,iv:PrWDPQxILw5l7+7U55olAXnmR86Ti66NGlNUI5iL4RA=,tag:QDDp2MCtY0NVjGGnIxZAVQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age105t9ftu7x77wqjsvkvgl9w9wz6thuqv5pzxc5ygtvyseakdkdgkqm99drf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBla1JYVWk4TEh1RlE3eHUw
            SDliWkhBaGhMWkhsQ0RrZ2xpd2lKVklkc2hFCkV5R3FqTjNhNmZRWGozNC9SVnE0
            Y05CVmFOcWZyMGhiQncxRDNWcHpULzAKLS0tIG1TLyt1aGpjYXJpTlZyMHdOc1RY
            WUYzWUc3UjRzU2gwYmhqOHNQQlJ5bGMKNufDNwqvU7+ien/Lv4izgsqAVTbjqACx
            vRuDz+yrUbOMSZgUvcKcyV0/zwVOmuMM90qDQnP8svu8y3SyS0OQDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-05T07:12:23Z"
    mac: ENC[AES256_GCM,data:NNsS8nNq1D2+HCrUcBEfdMFvsFI3seOOZJHlpqKPyDWYom4tCay7580CsN9UQtgRQ/KSpVu2y7f45/oWtviHsC46DCbj9LA4OQ1ZlRmxhTD7NXna6HlrxUCkMH+gInQYT7UCmZq4BtxX4vSVwRV5lwyref5uppSbgMKeTH5DieI=,iv:SLin4Xj0Nq7rtfywrf2ZKvZ0HOKIlJD99H5Jll0Ksoo=,tag:czF/n+lj7NeEeE7uiUCywg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
